# Generated by Django 4.2.2 on 2025-06-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.CharField(max_length=13, unique=True, verbose_name='track_number')),
                ('dates', models.DateTimeField(verbose_name='dates')),
                ('sender_country_id', models.IntegerField()),
                ('sender_country', models.CharField(max_length=196, verbose_name='title_country')),
                ('sender_address', models.CharField(max_length=192, verbose_name='sender_address')),
                ('sender_name', models.CharField(max_length=192, verbose_name='sender_name')),
                ('recipient_country_id', models.IntegerField()),
                ('recipient_country', models.CharField(max_length=196, verbose_name='title_country')),
                ('recipient_address', models.CharField(max_length=192, verbose_name='recipient_address')),
                ('recipient_name', models.CharField(max_length=192, verbose_name='recipient_name')),
                ('recipient_phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='recipient_phone')),
                ('final', models.CharField(max_length=192, verbose_name='final')),
            ],
            options={
                'db_table': 'view_package',
                'ordering': ['track_number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=196, unique=True, verbose_name='title_country')),
            ],
            options={
                'db_table': 'country',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=196, unique=True, verbose_name='title_status')),
            ],
            options={
                'db_table': 'status',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='status_title_8da31b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.CharField(max_length=13, unique=True, verbose_name='track_number')),
                ('dates', models.DateTimeField(verbose_name='datep')),
                ('sender_address', models.CharField(max_length=192, verbose_name='sender_address')),
                ('sender_name', models.CharField(max_length=192, verbose_name='sender_name')),
                ('recipient_address', models.CharField(max_length=192, verbose_name='recipient_address')),
                ('recipient_name', models.CharField(max_length=192, verbose_name='recipient_name')),
                ('recipient_phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='recipient_phone')),
                ('recipient_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_recipient_country', to='tracking.country')),
                ('sender_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_sender_country', to='tracking.country')),
            ],
            options={
                'db_table': 'package',
                'ordering': ['track_number'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datem', models.DateTimeField(verbose_name='dates')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details_movement')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_package', to='tracking.package')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_status', to='tracking.status')),
            ],
            options={
                'db_table': 'movement',
                'ordering': ['datem'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(verbose_name='telegram_id')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone_number')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=64, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='last_name')),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['first_name', 'last_name', 'phone_number'],
                'indexes': [models.Index(fields=['telegram_id'], name='customer_telegra_f5e35d_idx'), models.Index(fields=['phone_number'], name='customer_phone_n_d31982_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['title'], name='country_title_3c5f39_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['track_number'], name='package_track_n_3f5d66_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['sender_country'], name='package_sender__7ac26c_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['recipient_country'], name='package_recipie_1cfd98_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['package'], name='movement_package_220407_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['datem'], name='movement_datem_8708fe_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['status'], name='movement_status__e76714_idx'),
        ),
    ]
