# Generated by Django 4.2.2 on 2025-06-03 09:17
from pickle import FALSE, TRUE
from django.contrib.auth.models import User
from django.contrib.auth.models import Group

from django.db import migrations
# Подключаем модуль для работы с датой/веременем
from datetime import datetime, timedelta
# Подключаем модкль генерации случайных чисел
import random

# Подключаем модкль генерации случайных чисел
import random

def new_data(apps, schema_editor):
    try:
    
        # Суперпользователь id-1
        user = User.objects.create_superuser(username='root',
        email='post260222@mail.ru',
        password='SsNn5678+-@')
        print("Суперпользователь создан")
    
        # Группа менеджеров
        managers = Group.objects.get_or_create(name = 'Managers')
        managers = Group.objects.get(name='Managers')
        print("Группа менеджеров создана")
    
        # Пользователь с ролью менеджера id1
        user = User.objects.create_user(username='manager', password='Ss0066+-')
        managers.user_set.add(user)
        print("Менеджер добавлен в группу менеджеров")

        ##### Страна #####
    
        Country = apps.get_model("tracking", "Country")
   
        country = Country()
        country.title = 'Казахстан'    
        country.save()

        country = Country()
        country.title = 'Китай'    
        country.save()

        country = Country()
        country.title = 'США'    
        country.save()
    
        country = Country()
        country.title = 'ФРГ'    
        country.save()
    
        country = Country()
        country.title = 'Россия'    
        country.save()
    
        country = Country()
        country.title = 'Украина'    
        country.save()
    
        country = Country()
        country.title = 'Беларусь'    
        country.save()
    
        country = Country()
        country.title = 'Великобритания'    
        country.save()
    
        country = Country()
        country.title = 'Франция'    
        country.save()

        country = Country()
        country.title = 'Тайланд'    
        country.save()

        print("Страны добавлены")

        ##### Статус #####
    
        Status = apps.get_model("tracking", "Status")
   
        status = Status()
        status.title = 'Почтовое отправление принято в стране отправления'    
        status.save()

        status = Status()
        status.title = 'Прибыло в исходящее учреждение обмена в стране отправления'    
        status.save()

        status = Status()
        status.title = 'Отправлено в страну назначения'    
        status.save()
    
        status = Status()
        status.title = 'Принято почтовое отправление'    
        status.save()
    
        status = Status()
        status.title = 'Прошло таможенное оформление'    
        status.save()
    
        status = Status()
        status.title = 'Отправлено из центра сортировки'    
        status.save()
    
        status = Status()
        status.title = 'Прибыло в центр сортировки'    
        status.save()
    
        status = Status()
        status.title = 'Ожидает получателя в пункте выдачи'    
        status.save()
    
        status = Status()
        status.title = 'Вручено'    
        status.save()
    
        print("Статусы добавлены")

        ##### Посылка (почтовое отправление) #####

        from datetime import datetime, timedelta
        import random

        Package = apps.get_model("tracking", "Package")
        Movement = apps.get_model("tracking", "Movement")

        package = Package()
        package.id = 1
        package.track_number = 'RE' + str(random.randint(100000000,999999999)) + 'CN'
        package.dates = datetime.now() + timedelta(days=-30) + timedelta(minutes=random.randint(1, 240))
        package.sender_country_id = 2
        package.sender_address = 'Changhan Rd, Fangshan District, Beijing, Китай, 102445'
        package.sender_name = 'Zhang  Lina'
        package.recipient_country_id = 1
        package.recipient_address = 'Magnitogorsk, Raduzhnaya st., bldg. 25, apt. 74'
        package.recipient_name = 'Kuznecova Veronika'
        package.recipient_phone = '+79031234567'    
        package.save()

        for i in range(9):
            movement = Movement()
            movement.package_id = package.id
            movement.datem = datetime.now() + timedelta(days=(-29+i)) + timedelta(minutes=random.randint(1, 240))
            movement.status_id = (i+1)       
            movement.save()
        print("Посылки " + package.track_number + " добавлена")

        package = Package()
        package.id = 2
        package.track_number = 'RE' + str(random.randint(100000000,999999999)) + 'CN'
        package.dates = datetime.now() + timedelta(days=-29) + timedelta(minutes=random.randint(1, 240))
        package.sender_country_id = 2
        package.sender_address = 'Jingshen Rd, Fangshan District, Beijing, Китай, 102445'
        package.sender_name = 'Zhao Qian'
        package.recipient_country_id = 1
        package.recipient_address = 'Novocherkassk, Vishnevaya st., bldg. 24, apt. 205'
        package.recipient_name = 'Kazakova Polina'
        package.recipient_phone = '+79031234567'    
        package.save()

        for i in range(9):
            movement = Movement()
            movement.package_id = package.id
            movement.datem = datetime.now() + timedelta(days=(-28+i)) + timedelta(minutes=random.randint(1, 240))
            movement.status_id = (i+1)       
            movement.save()
        print("Посылка " + package.track_number + " добавлена")

        package = Package()
        package.id = 3
        package.track_number = 'RE' + str(random.randint(100000000,999999999)) + 'CN'
        package.dates = datetime.now() + timedelta(days=-28) + timedelta(minutes=random.randint(1, 240))
        package.sender_country_id = 2
        package.sender_address = 'Changhan Rd, Fangshan District, Beijing, Китай, 102445'
        package.sender_name = 'Sun Li'
        package.recipient_country_id = 1
        package.recipient_address = 'Biysk, Rabochaya st., bldg. 12, apt. 109'
        package.recipient_name = 'Belyaeva Arina'
        package.recipient_phone = '+79031234567'    
        package.save()

        for i in range(7):
            movement = Movement()
            movement.package_id = package.id
            movement.datem = datetime.now() + timedelta(days=(-27+i)) + timedelta(minutes=random.randint(1, 240))
            movement.status_id = (i+1)       
            movement.save()
        print("Посылка " + package.track_number + " добавлена")

        package = Package()
        package.id = 4
        package.track_number = 'RE' + str(random.randint(100000000,999999999)) + 'CN'
        package.dates = datetime.now() + timedelta(days=-28) + timedelta(minutes=random.randint(1, 240))
        package.sender_country_id = 2
        package.sender_address = 'Changyang Rd, Fangshan District, Beijing, Китай, 102442'
        package.sender_name = 'Zhou Wu'
        package.recipient_country_id = 1
        package.recipient_address = 'г. Ульяновск, Озерная ул., д. 21 кв.74'
        package.recipient_name = 'Popov Mihail'
        package.recipient_phone = '+79131234567'    
        package.save()

        for i in range(7):
            movement = Movement()
            movement.package_id = package.id
            movement.datem = datetime.now() + timedelta(days=(-27+i)) + timedelta(minutes=random.randint(1, 240))
            movement.status_id = (i+1)       
            movement.save()
        print("Посылка " + package.track_number + " добавлена")

        package = Package()
        package.id = 5
        package.track_number = 'RE' + str(random.randint(100000000,999999999)) + 'CN'
        package.dates = datetime.now() + timedelta(days=-27) + timedelta(minutes=random.randint(1, 240))
        package.sender_country_id = 2
        package.sender_address = 'Q56P+JC9, Fangshan District, Beijing, Китай, 102445'
        package.sender_name = 'Zheng Wang'
        package.recipient_country_id = 1
        package.recipient_address = 'Rybinsk, Komsomolskaya st., bldg. 11, apt. 77'
        package.recipient_name = 'Baranov Il\'ya'
        package.recipient_phone = '+79131234567'    
        package.save()

        for i in range(6):
            movement = Movement()
            movement.package_id = package.id
            movement.datem = datetime.now() + timedelta(days=(-26+i)) + timedelta(minutes=random.randint(1, 240))
            movement.status_id = (i+1)       
            movement.save()
        print("Посылка " + package.track_number + " добавлена")

        package = Package()
        package.id = 6
        package.track_number = 'RE' + str(random.randint(100000000,999999999)) + 'CN'
        package.dates = datetime.now() + timedelta(days=-26) + timedelta(minutes=random.randint(1, 240))
        package.sender_country_id = 2
        package.sender_address = 'Changyang Rd, Fangshan District, Beijing, Китай, 102442'
        package.sender_name = 'Chu Wei'
        package.recipient_country_id = 1
        package.recipient_address = 'Stavropol, Novaya st., bldg. 21, apt. 160'
        package.recipient_name = 'Yakovlev Roman'
        package.recipient_phone = '+79131234567'    
        package.save()

        for i in range(5):
            movement = Movement()
            movement.package_id = package.id
            movement.datem = datetime.now() + timedelta(days=(-25+i)) + timedelta(minutes=random.randint(1, 240))
            movement.status_id = (i+1)       
            movement.save()
        print("Посылка " + package.track_number + " добавлена")

        package = Package()
        package.id = 7
        package.track_number = 'RE' + str(random.randint(100000000,999999999)) + 'CN'
        package.dates = datetime.now() + timedelta(days=-25) + timedelta(minutes=random.randint(1, 240))
        package.sender_country_id = 2
        package.sender_address = 'Xiangyun St, Fangshan District, Beijing, Китай, 102442'
        package.sender_name = 'Jiang Shen'
        package.recipient_country_id = 1
        package.recipient_address = 'Lipetsk, Chkalova st., bldg. 2, apt. 151'
        package.recipient_name = 'Kryukov Andrej'
        package.recipient_phone = '+79037654321'    
        package.save()

        for i in range(4):
            movement = Movement()
            movement.package_id = package.id
            movement.datem = datetime.now() + timedelta(days=(-24+i)) + timedelta(minutes=random.randint(1, 240))
            movement.status_id = (i+1)       
            movement.save()
        print("Посылка " + package.track_number + " добавлена")

        package = Package()
        package.id = 8
        package.track_number = 'RE' + str(random.randint(100000000,999999999)) + 'CN'
        package.dates = datetime.now() + timedelta(days=-24) + timedelta(minutes=random.randint(1, 240))
        package.sender_country_id = 2
        package.sender_address = 'Changyang Rd, Fangshan District, Beijing, Китай, 102442'
        package.sender_name = 'Han Yang'
        package.recipient_country_id = 1
        package.recipient_address = 'Bataysk, Yuzhnaya st., bldg. 22, apt. 90'
        package.recipient_name = 'Gribova Eva'
        package.recipient_phone = '+79038526547'    
        package.save()

        for i in range(4):
            movement = Movement()
            movement.package_id = package.id
            movement.datem = datetime.now() + timedelta(days=(-23+i)) + timedelta(minutes=random.randint(1, 240))
            movement.status_id = (i+1)       
            movement.save()
        print("Посылка " + package.track_number + " добавлена")

        package = Package()
        package.id = 9
        package.track_number = 'RE' + str(random.randint(100000000,999999999)) + 'CN'
        package.dates = datetime.now() + timedelta(days=-23) + timedelta(minutes=random.randint(1, 240))
        package.sender_country_id = 2
        package.sender_address = 'Jingshen Rd, Fangshan District, Beijing, Китай, 102442'
        package.sender_name = 'Yu Xu'
        package.recipient_country_id = 1
        package.recipient_address = 'Chita, Ozernaya st., no. 9, apt. 42'
        package.recipient_name = 'Shirokov Dmitrij'
        package.recipient_phone = '+79039513572'    
        package.save()

        for i in range(3):
            movement = Movement()
            movement.package_id = package.id
            movement.datem = datetime.now() + timedelta(days=(-22+i)) + timedelta(minutes=random.randint(1, 240))
            movement.status_id = (i+1)       
            movement.save()
        print("Посылка " + package.track_number + " добавлена")

        package = Package()
        package.id = 10
        package.track_number = 'RE' + str(random.randint(100000000,999999999)) + 'CN'
        package.dates = datetime.now() + timedelta(days=-22) + timedelta(minutes=random.randint(1, 240))
        package.sender_country_id = 2
        package.sender_address = 'Changyang Rd, Fangshan District, Beijing, Китай, 102442'
        package.sender_name = 'He Lu'
        package.recipient_country_id = 1
        package.recipient_address = 'Nizhny Novgorod, Priozernaya st., bldg. 1, apt. 71'
        package.recipient_name = 'Maksimov Nikita'
        package.recipient_phone = '+79036541239'    
        package.save()

        for i in range(3):
            movement = Movement()
            movement.package_id = package.id
            movement.datem = datetime.now() + timedelta(days=(-21+i)) + timedelta(minutes=random.randint(1, 240))
            movement.status_id = (i+1)       
            movement.save()
        print("Посылка " + package.track_number + " добавлена")

    except Exception as error:
        print(error)

class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(new_data),
        ## SQLite
        #migrations.RunSQL("""CREATE VIEW view_package AS
        #SELECT package.id, track_number, dates, sender_country_id, cs.title AS sender_country, sender_address,  sender_name, recipient_country_id, cr.title AS recipient_country, recipient_address, recipient_name, recipient_phone,
        #(SELECT strftime('%d.%m.%Y %H:%M', datem) || " " || title FROM movement LEFT JOIN status ON movement.status_id =  status.id WHERE datem=(SELECT Max(datem) FROM movement m WHERE m.package_id=package.id)) AS final
        #FROM package LEFT JOIN country cs ON package.sender_country_id = cs.id
        #LEFT JOIN country cr ON package.recipient_country_id = cr.id
        #"""),
        ## PostgreSQL
        migrations.RunSQL("""CREATE VIEW view_package AS
        SELECT package.id, track_number, dates, sender_country_id, cs.title AS sender_country, sender_address,  sender_name, recipient_country_id, cr.title AS recipient_country, recipient_address, recipient_name, recipient_phone,
        (SELECT to_char(datem, 'DD.MM.YYYY HH12:MI:SS') || ' '  || title FROM movement LEFT JOIN status ON movement.status_id =  status.id WHERE datem=(SELECT Max(datem) FROM movement m WHERE m.package_id=package.id)) AS final
        FROM package LEFT JOIN country cs ON package.sender_country_id = cs.id
        LEFT JOIN country cr ON package.recipient_country_id = cr.id
        """),

    ]
